### ISSUE TITLE
jetsonの時刻設定が必要

### ISSUE THREAD

**Issue by sakakendo0321** [teamET/2018.meister#18]
ntpではデフォルトのポートが閉じられているそうなのでポートを変更するか，dateコマンドで主導的に設定する必要性があるみたい
https://hydrocul.github.io/wiki/commands/date.html

**Comment by sakakendo0321** [comment]
やった

**Comment by sakakendo0321** [comment]
https://qiita.com/megu_ma/items/bb902740ee7de9ddd102

```
$ sudo hwclock --show
Sun 06 Jan 2019 04:02:18 PM JST  .900662 seconds```

**Comment by Spacekoki** [comment]
http://www14.plala.or.jp/campus-note/vine_linux/system/clock.html

**Comment by sakakendo0321** [comment]
設定できた
