### ISSUE TITLE
zed のライブラリのインストール

### ISSUE THREAD

**Issue by sakakendo0321** [teamET/2018.meister#23]
zed のライブラリのインストール

_Originally posted by @sakakendo0321 in https://github.com/teamET/2018.meister/issues/10#issuecomment-463025451_

**Comment by sakakendo0321** [comment]
https://www.stereolabs.com/docs/getting-started/installation/

**Comment by sakakendo0321** [comment]
https://www.stereolabs.com/developers/release/archives/

**Comment by junichi** [comment]
![depthviewer_sbs_11549_1242_13-02-2019-18-14-09](https://user-images.githubusercontent.com/12451915/52700891-505add00-2fbc-11e9-82ca-0a2f38260355.png)
![screenshot from 2019-02-13 18-16-29](https://user-images.githubusercontent.com/12451915/52700903-56e95480-2fbc-11e9-9a86-b1378e942a6e.png)

zed sdk install 終了
