### ISSUE TITLE
WARNING ! Required ZED SDK version: 2.7

### ISSUE THREAD

**Issue by sakakendo0321** [teamET/2018.meister#24]
> https://www.stereolabs.com/docs/getting-started/python-development/
> 
> ```
> (zed-python-api) nvidia@tegra-ubuntu:~/workspace/zed-python-api$ python3 setup.py build ; python3 setup.py install
> WARNING ! Required ZED SDK version: 2.7
> ZED SDK detected: = 2;.= 1;.= 2;
> Aborting
> WARNING ! Required ZED SDK version: 2.7
> ZED SDK detected: = 2;.= 1;.= 2;
> Aborting```
> ```

zedのサンプル自体は動いたのだがpythonのラッパーをインストールしようと思ったら
zed sdkのバージョンをもっと高くしろと怒られた

_Originally posted by @sakakendo0321 in https://github.com/teamET/2018.meister/issues/10#issuecomment-463192572_

**Comment by sakakendo0321** [comment]
Jetpack3.1を使っているのでzed sdkは2.1~2.3まで使える
zed-python-sdk のタグ指定で古いのに戻せば使えるようになると思う

https://www.stereolabs.com/developers/release/archives/

https://github.com/stereolabs/zed-python-api/tree/v2.3.x

**Comment by IwasakiYuuki** [comment]
一応pythonでzed-python-apiは動いた。
