### ISSUE TITLE
pyssc32 - python2問題

### ISSUE THREAD

**Issue by sakakendo0321** [teamET/2018.meister#26]
lynxmotionの依存ファイルであるpyssc32がpython2でしか使うことができないので，難かしらの方法でpython3から呼び出せるようにしたい

![](https://github.com/cberner/lynxmotion/blob/master/lynxmotion/al5d.py)
```
(2018.meister) nvidia@tegra-ubuntu:~/workspace/2018.meister$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssc32
>>>
```

_Originally posted by @sakakendo0321 in https://github.com/teamET/2018.meister/issues/21#issuecomment-463112292_

**Comment by sakakendo0321** [comment]
disutilsを使ってcythonでビルドしようと思ったけどpython2でのdisutilsが見当たらなかったのでいったん保留

**Comment by sakakendo0321** [comment]
@IwasakiYuuki udp

**Comment by IwasakiYuuki** [comment]
@sakakendo0321 UDPサーバのpull request送ったからちょっと見てみて

**Comment by sakakendo0321** [comment]
送信データ

`"関数名/{x:100,y:200,z:400}"`

example 

`"move/{x:100,y:200,z:400}"`

```
func,data=self.sock.recv(self.data_size).split("/")
locals()[func](**json.loads(data))
```

**Comment by sakakendo0321** [comment]
udp serverを立てて、processを分離させることで解決する
